#!/usr/bin/env python3
"""
LINT-17 — coverage: every prose caption resolves to a page OR a ledger terminal.
S6 · R12 (why-missed class-2 defense; alias LINT-S6-coverage; S9 R8 roster row 17).
FAIL-CLOSED.

The named-but-no-page drift class (O1: ~70-80 captions grew in prose with no
page, invisible to CI). R12's defense: the seed scanner becomes a CI lint — a
prose caption resolving to NO page fails the build UNLESS the S6 coverage ledger
(`_run/s6-coverage-ledger.json`, R11) records a terminal non-page state for it.

Resolution, per distinct party-v-party caption found in content/**/*.md prose
(bare or wikilinked; junk left-parties and citation-format examples filtered):

  (1) PAGE — CorpusIndex.resolve() succeeds (stem/title/alias), OR a corpus page
      title is a token-subsequence-equal variant of the caption (official
      long-form / comma-company-fragment / trailing-token artifacts collapse to
      their page: "Marcus v. Search Warrant of Property" -> "Marcus v. Search
      Warrant"; "Inc. v. New York" -> "Lo-Ji Sales, Inc. v. New York"). Token
      alignment (not substring) so "United States v. White" is NOT covered by a
      "United States v. Whitehead" page.  -> PASS.
  (2) LEDGER ALLOWLIST — the caption (or an alias) is a NON-authored terminal row
      in the R11 ledger (brief-mention | excluded-remit | unverifiable | removed |
      folded-alias | watch) OR a frozen `corpus_mention_baseline` row (the S6-close
      snapshot of page-less bare-mentions S8 plain-links).  -> PASS.
  (3) neither  -> HIGH ("prose caption resolves to no page and no ledger terminal
      state — coverage drift [S6 R12]"). Fails the build.

The allowlist is a FROZEN snapshot: the ledger + baseline are committed by
`_overhaul2/scripts/build_coverage_ledger.py`, not regenerated by this lint, so a
NEW bare caption grown after S6 close is not silently allowlisted — it fails CI
until it earns a page or a ledger disposition.

Usage: python3 lint17_coverage.py [glob ...]   ( --self-test for the fixture gate )
"""

import json
import os
import re
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import _common as c  # noqa: E402

LINT = "LINT-17"
LEDGER_REL = os.path.join("_run", "s6-coverage-ledger.json")

# left-party tokens that mark a non-case / fragment (defensive; mirrors LINT-5
# plus bare company-suffix fragments produced by comma-splitting a corporate
# party — those are recovered by the token-subsequence page-variant match).
_JUNK_LEFT = {"see", "cf", "e.g", "id", "compare", "accord", "but", "inc",
              "co", "corp", "llc", "ltd", "n.a", "l.p"}


def _toks(s):
    """Alphanumeric tokens, lowercased, apostrophes folded. 'v' is kept so the
    v-separator anchors the party alignment."""
    return re.findall(r"[a-z0-9]+", (s or "").lower().replace("’", "'"))


def _is_contiguous_sublist(a, b):
    """True iff token list `a` is a contiguous sublist of `b`."""
    la, lb = len(a), len(b)
    if not a or la > lb:
        return False
    for i in range(lb - la + 1):
        if b[i:i + la] == a:
            return True
    return False


def extract_captions(text):
    """Yield distinct party-v-party captions from a page body (bare prose and
    wikilink targets), filtering junk left-parties and single-letter fragments.
    Bare names are scanned on link/code-masked lines so already-linked captions
    are still surfaced (coverage is about the CAPTION, not the link)."""
    _fm, body, _start = c.split_frontmatter(text)
    fenced = c.fenced_line_numbers(body.split("\n"))
    caps = set()
    for i, line in enumerate(body.split("\n")):
        if i in fenced:
            continue
        masked = c.mask_links_and_code(line)
        for m in c.CASE_RE.finditer(masked):
            _add_caption(caps, m.group(1), m.group(0))
        for m in c.WIKILINK_RE.finditer(line):
            inner = m.group(1).split("|", 1)[0].split("#", 1)[0].strip()
            mm = c.CASE_RE.match(inner)
            if mm and mm.group(0).strip() == inner:
                _add_caption(caps, mm.group(1), inner)
    return caps


def _add_caption(caps, left, full):
    lt = left.strip().lower().rstrip(".")
    if lt in _JUNK_LEFT or len(lt) <= 1:
        return
    caps.add(full.strip())


def build_page_tokenlists(idx):
    """Token lists for every resolvable page name form (stem + title/topic +
    aliases), for the token-subsequence variant match."""
    out = []
    for path in c.iter_markdown_files(None):
        stem = os.path.splitext(os.path.basename(path))[0]
        out.append(_toks(stem))
        fm, _b, _s = c.split_frontmatter(c.read_text(path))
        for k in ("title", "topic"):
            v = fm.get(k)
            if isinstance(v, str) and v.strip():
                out.append(_toks(v))
        al = fm.get("aliases")
        if isinstance(al, list):
            for a in al:
                if isinstance(a, str) and a.strip():
                    out.append(_toks(a))
        elif isinstance(al, str) and al.strip():
            out.append(_toks(al))
    return [t for t in out if "v" in t]


def covered_by_page(caption, idx, page_tokenlists):
    """(1) exact resolve, or (2) token-subsequence variant against page titles."""
    if idx is not None and idx.resolve(caption) is not None:
        return True
    ct = _toks(caption)
    if "v" not in ct:
        return False
    for pt in page_tokenlists:
        if _is_contiguous_sublist(ct, pt) or _is_contiguous_sublist(pt, ct):
            return True
    return False


# The known non-authored terminal states (module docstring / S6 R11). Any other
# `terminal` value on a ledger row is un-vetted and must fail closed rather than
# silently allowlist a caption as covered.
_NONAUTHORED_TERMINALS = {
    "brief-mention", "excluded-remit", "unverifiable",
    "removed", "folded-alias", "watch",
}


def load_allowlist(ledger_path=None):
    """Normalized caption/alias set of every NON-authored ledger row + every
    frozen corpus_mention_baseline row. Returns (allowlist:set, error:str|None)."""
    path = ledger_path or os.path.join(c.REPO_ROOT, LEDGER_REL)
    if not os.path.isfile(path):
        return set(), ("coverage ledger missing: %s not found — LINT-17 cannot "
                       "allowlist non-page terminals [S6 R11/R12]" % LEDGER_REL)
    try:
        with open(path, encoding="utf-8") as f:
            led = json.load(f)
    except (OSError, json.JSONDecodeError) as exc:
        return set(), "coverage ledger unreadable (%s): %s" % (LEDGER_REL, exc)
    if not isinstance(led, dict):
        return set(), "coverage ledger malformed (%s): expected a JSON object" % LEDGER_REL
    allow = set()
    for row in led.get("rows", []):
        if not isinstance(row, dict):
            return set(), "coverage ledger malformed (%s): non-dict row" % LEDGER_REL
        term = row.get("terminal")
        if term == "authored":
            continue
        if term not in _NONAUTHORED_TERMINALS:
            return set(), ("coverage ledger row has unknown terminal state %r "
                           "[S6 R11]" % term)
        _add_allow(allow, row)
    for row in led.get("corpus_mention_baseline", []):
        if not isinstance(row, dict):
            return set(), "coverage ledger malformed (%s): non-dict baseline row" % LEDGER_REL
        _add_allow(allow, row)
    return allow, None


def _add_allow(allow, row):
    for key in ("caption", "canonical"):
        if row.get(key):
            allow.add(c.CorpusIndex.norm(row[key]))
    for a in row.get("aliases", []) or []:
        allow.add(c.CorpusIndex.norm(a))


def classify(caption, idx, page_tokenlists, allowlist):
    """Return 'page' | 'allowlist' | 'MISSING' for one caption."""
    if covered_by_page(caption, idx, page_tokenlists):
        return "page"
    if c.CorpusIndex.norm(caption) in allowlist:
        return "allowlist"
    return "MISSING"


def run(paths=None):
    idx = c.build_corpus_index()
    page_tokenlists = build_page_tokenlists(idx)
    allowlist, err = load_allowlist()
    out = []
    if err:
        # ledger absent/broken: fail-closed HIGH once (do not scan blind)
        out.append(c.make_violation(
            LINT, os.path.join(c.REPO_ROOT, LEDGER_REL), 1, c.HIGH, err))
        return out
    for path in c.iter_markdown_files(paths):
        text = c.read_text(path)
        for caption in sorted(extract_captions(text)):
            if classify(caption, idx, page_tokenlists, allowlist) == "MISSING":
                out.append(c.make_violation(
                    LINT, path, 1, c.HIGH,
                    "prose caption '%s' resolves to no page and no coverage-"
                    "ledger terminal state — named-but-no-page drift; author it "
                    "or record a ledger terminal (R11) [S6 R12]" % caption[:80]))
    return out


def self_test():
    ok = True

    def check(name, got, want):
        nonlocal ok
        p = got == want
        ok = ok and p
        sys.stderr.write("[self-test] %-40s -> %s (got=%s want=%s)\n"
                         % (name, "OK" if p else "MISMATCH", got, want))

    # (1) pure classify() logic — hermetic, no corpus dependency
    pages = [_toks("Foo v. Bar"), _toks("Lo-Ji Sales, Inc. v. New York"),
             _toks("Mapp v. Ohio")]
    allow = {c.CorpusIndex.norm("Legacy v. Mention")}
    check("exact-page-resolves", classify("Foo v. Bar", None, pages, allow), "page")
    check("variant-company-fragment", classify("Inc. v. New York", None, pages, allow), "page")
    check("variant-trailing-overrun", classify("Mapp v. Ohio. Identity", None, pages, allow), "page")
    check("ledger-allowlisted", classify("Legacy v. Mention", None, pages, allow), "allowlist")
    check("new-bare-caption-fails", classify("Zzyzx v. Nowhere", None, pages, allow), "MISSING")
    # token alignment must NOT over-cover a distinct surname
    check("no-substring-falsecover", classify("United States v. White", None,
          [_toks("United States v. Whitehead")], set()), "MISSING")
    # a folded-alias caption is NOT covered by its longer-name survivor page
    check("fold-not-covered-by-survivor", classify("United States v. Davis", None,
          [_toks("United States v. Howard Davis")], set()), "MISSING")

    # (2) fixture scan — a synthetic new bare caption in a real fixture FAILS,
    #     an allowlisted one PASSES (uses the real corpus page-index so the
    #     fixture's control caption is genuinely page-less)
    idx = c.build_corpus_index()
    page_tokenlists = build_page_tokenlists(idx)
    fail_fx = os.path.join(c.HERE, "fixtures", "lint-17-fail.md")
    pass_fx = os.path.join(c.HERE, "fixtures", "lint-17-pass.md")
    synth_allow = {c.CorpusIndex.norm("Allowlisted v. Terminal")}
    if os.path.isfile(fail_fx):
        caps = extract_captions(c.read_text(fail_fx))
        miss = [x for x in caps
                if classify(x, idx, page_tokenlists, synth_allow) == "MISSING"]
        check("fixture-fail-has-missing", len(miss) >= 1, True)
    else:
        check("fixture-fail-present", False, True)
    if os.path.isfile(pass_fx):
        caps = extract_captions(c.read_text(pass_fx))
        miss = [x for x in caps
                if classify(x, idx, page_tokenlists, synth_allow) == "MISSING"]
        check("fixture-pass-no-missing", miss, [])
    else:
        check("fixture-pass-present", False, True)

    # (3) load_allowlist() fail-closed gate — the actual ledger-parsing path, the
    #     highest-value thing to self-test. Each malformed/unexpected ledger must
    #     return a non-None error, never a silent empty allowlist.
    def allow_err(name, content, want_err):
        with tempfile.NamedTemporaryFile("w", suffix=".json", delete=False,
                                         encoding="utf-8") as tf:
            tf.write(content)
            tmp = tf.name
        try:
            _, err = load_allowlist(tmp)
        finally:
            os.unlink(tmp)
        check(name, err is not None, want_err)

    # missing ledger file (path does not exist) -> error
    missing_path = os.path.join(tempfile.gettempdir(), "lint17-nonexistent-ledger.json")
    if os.path.exists(missing_path):
        os.unlink(missing_path)
    _, merr = load_allowlist(missing_path)
    check("load_allowlist-missing-ledger", merr is not None, True)
    allow_err("load_allowlist-malformed-json", "{ not: json", True)
    allow_err("load_allowlist-top-level-not-object", '["a", "list"]', True)
    allow_err("load_allowlist-non-dict-row",
              json.dumps({"rows": ["notadict"]}), True)
    allow_err("load_allowlist-unknown-terminal",
              json.dumps({"rows": [{"terminal": "bogus", "caption": "X v. Y"}]}), True)
    allow_err("load_allowlist-non-dict-baseline",
              json.dumps({"corpus_mention_baseline": ["notadict"]}), True)
    allow_err("load_allowlist-valid-nonauthored",
              json.dumps({"rows": [{"terminal": "brief-mention", "caption": "X v. Y"}]}), False)

    sys.stderr.write("[self-test] %s\n" % ("PASS" if ok else "FAIL"))
    return 0 if ok else 1


if __name__ == "__main__":
    if "--self-test" in sys.argv[1:]:
        sys.exit(self_test())
    c.cli_main(run, LINT)
